version: '3.1'

services:
  knu_shoppingmall:
    image: changjinkube/knu_shoppingmall:nodejs1.0
    # build: ./nodejs
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      - /media/changjin/ubuntu_1TB/DB/nodejs/uploads:/github/uploads/uploads
    ports:
      - 80:3000
      - 5000:5000
      - 922:80
  knu_blog:
    image: changjinkube/knu_shoppingmall:flask
    # build: ./Flask
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
      - 5051:5051
      - 923:80

networks:
  default:
    external:
      name: mongo_default